image: gitpod/workspace-dotnet:latest

tasks:
  - name: Postinstall .NET 6.0 and dev certificates
    init: |
      mkdir -p /home/gitpod/dotnet &&  curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --runtime aspnetcore --version 6.0.12 --install-dir /home/gitpod/dotnet
      dotnet dev-certs https 
      dotnet restore
